AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Express.js JWT Auth API on AWS Lambda with DynamoDB

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: nodejs20.x

Resources:
  ExpressAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: lambda.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production
          USERS_TABLE: !Ref UsersTable
          ITEMS_TABLE: !Ref ItemsTable
          JWT_SECRET: "change_this_secret_in_aws_console_or_ssm"
          JWT_EXPIRES_IN: "24h"

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: express-jwt-users
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: express-jwt-items
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  WebEndpoint:
    Description: "API Gateway Endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
